config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :listings, only: [ :index ]
  resources :journeys, only: [ :index, :show, :create, :edit, :update, :destroy] do
    member do
      get :route_email
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/my-journeys', to: 'journeys#my_journeys'
  get '/editorial', to: 'pages#editorial'

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :listing_tags, dependent: :destroy
  has_many :listings, through: :listing_tags
end

app/views/shared/_banner.html.erb
<!-- BANNER -->
<div class="justify-content-center">
  <div class="col-xl-12">

    <% if user_signed_in? %>

      <div id="Welcome" class="tabcontent" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
        url(https://images.unsplash.com/photo-1585658771091-319073dc8714?ixlib=rb-1.2.1&ixid=MnwxM[…]90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1368&q=80)">
        <h1>Welcome Back</h1>
        <h2><%= current_user.username%>🚴</h2>
        <p> Time to discover the sights and eats of Singapore.</p>
          <div class="btn btn-success">
            <a href="/my-journeys">All My Routes</a>
          </div>
      </div>

    <% else %>

    <div id="Welcome" class="tabcontent" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
      url(https://images.unsplash.com/photo-1585658771091-319073dc8714?ixlib=rb-1.2.1&ixid=MnwxM[…]90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1368&q=80)">
      <h1>Explore Singapore on bicycle</h1>
      <p>Discover the sights and eats of Singapore.</p>
        <div class="btn btn-success">
          <a href="/users/sign_up">Signup for free</a>
        </div>
    </div>

    <% end %>
  </div>
</div>

<!-- BANNER TABS x 4 -->
<!--
      <div id="tab1" class="tabcontent" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1600x900/?bicycle,cafe,fund)">
        <h1>See all journeys</h1>
        <p>Be inspired by some of the most interesting routes created by our riders!</p>
        <a href="/journeys" style="width: 100%">Let's ride!</a>
      </div>

      <div id="tab2" class="tabcontent" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1600x900/?merlon,singapore,city)">
        <h1>Support Local</h1>
        <p>Check out all the yummlicious makans in our local hawker centers! </p>
      </div>

      <div id="tab3" class="tabcontent" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1600x900/?singapore,nightscape,city)">
        <h1>The amazing nightscape of Singapore skyline</h1>
        <p>Let's go when the clock strikes twelve!</p>
      </div>

    </div>
  </div>

</div>

<button class="tablink" onclick="openTab('Welcome', this, 'red')" id="defaultOpen">RideNow!</button>
<button class="tablink" onclick="openTab('tab1', this, 'green')">All Routes</button>
<button class="tablink" onclick="openTab('tab2', this, 'blue')">Support Local</button>
<button class="tablink" onclick="openTab('tab3', this, 'orange')">Nightscape</button>


<script>
  function openTab(tabName,elmnt,color) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablink");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].style.backgroundColor = "";
    }
    document.getElementById(tabName).style.display = "block";
    elmnt.style.backgroundColor = color;

  }
      // Get the element with id="defaultOpen" and click on it
      document.getElementById("defaultOpen").click();
    </script>


  -->

app/views/shared/_card.html.erb
    <!-- LIST ALL PUBLIC ROUTES - PRIVACY FALSE -->

    <% @journeys.where(privacy: false).limit(12).each do |journey| %>

    <div class="col-lg-2">
      <div class="card">
        <img class="card-img-top" src="<%=journey.route_url%>">
        <div class="card-body">
          <h6 class="card-title">
            <%= link_to "#{journey.name}", journey %>
          </h6>
          <p>
            From: <%= journey.origin %> </br>
            To: <%= journey.destination %>
          </p>
          <div class="card-avatar">
            <% user = User.find(journey.user_id)%>
            <%= render "shared/user-avatar", user: user %>
          </div>
        </div>
        <div class="card-footer">
          <small>
            <%= link_to "see route", journey %>
          </small>
        </div>
      </div>
    </div>

    <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<div class="info-window">

  <h6><%= listing.name %></h6>
  <p> <%= listing.description %> </p>


</div>

app/views/shared/_landingpage-routecard.html.erb
<div class="card-group">
      <h3>Our Popular Routes<small><em><%= link_to "(see all)", journeys_path %></em></small></h3>
  </div>

    <!-- LIST ALL PUBLIC ROUTES - PRIVACY FALSE -->
 <div class="container-landing">
    <% @journeys.where(privacy: false).limit(5).each do |journey| %>
      <div class="card-landing">
        <img class="card-img-landing" src="<%=journey.route_url%>">
           <div class="card-avatar-landing">
              <% user = User.find(journey.user_id)%>
              <%= render "shared/user-avatar", user: user %>
            </div>
            <h6 class="card-title-landing">
              <%= link_to "#{journey.name}", journey %>
            </h6>
            <div class="card-body-landing">
              <small>From: <%= journey.origin.titleize %> </small>
              <small>To: <%= journey.destination.titleize %></small>
            </div>
          <div class="btn btn-success"><%= link_to "see route", journey %></div>
      </div>
    <% end %>
  </div>

app/views/shared/_listing-image.html.erb
<% if listing.photo.attached? %>
<img class="card-img-top" src="https://res.cloudinary.com/dcm2heeuf/image/upload/v1620723373/<%=listing.photo.key %>" href="/listing">
<% else %>
<img class="card-img-top" src="https://source.unsplash.com/400x300/?<%=listing.name%>" />
<% end %>

app/views/shared/_map.html.erb
<div id="map-listing"
  data-start="<%= start.to_json %>"
  data-end="<%= end_location.to_json %>"
  data-fitpoints="<%= fit_points.to_json %>"
  data-listingmarkers="<%= listing_markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "https://i.ibb.co/rHvy278/Asset-2-300x-8.png" %>
  <% end %>

  <%= render 'shared/search-start-end' %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item dropdown ml-3">
        <% if current_user.avatar.attached? %>
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup=true aria-expanded=false src="https://res.cloudinary.com/dcm2heeuf/image/upload/v1620723373/<%=current_user.avatar.key %>">
        <% else %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "All My Routes", "/my-journeys", class: "dropdown-item" %>
          <hr>
          <%= link_to "Edit Profile", "/users/edit", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Signup or Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_route_tile.html.erb
 <div id="listing-<%=listing.id%>" class="route-tile" data-listing-id="<%=listing.id%>">
  <div class="route-tile-info d-flex flex-column justify-content-between">
    <div class="card-title">
      <h6>
        <strong><%= listing.name%></strong>
      </h6>
    </div>
    <div class="card-text ">
      <small>
        <%= listing.address %>
      </small>
      <div class="d-flex justify-content-between">
        <small>
          <div class="badge badge-pill badge-success">
            <%= listing.tags.map(&:name).join('') %>
          </div>
        </small>
        <div class="form-check">
          Select <%= check_box_tag 'listing_ids[]', listing.id %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search-start-end.html.erb
<% if user_signed_in? %>
  <div class="container-search" style="position: relative; right:10px">
    <button class="btn btn-flat" data-toggle="collapse" data-target="#collapseDropDownSearch">Start New Journey</button>
    <div class="collapse" id="collapseDropDownSearch">
      <div class="card-search" id = "drop-down-filtersearch">
        <%= form_with url: "/listings", method: :get, local: true, class: 'simple_form search drop-down-form' do |form| %>
          <div class="search-input">
            <label for="start">Start</label>
            <%= form.text_field :start, id: "start", name: "start", required: 3%>
            <label for="end">End</label>
            <%= form.text_field :end, id: "end", name: "end", required: 3 %>
            <button type="submit" class="btn btn-ghost"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>  
    </div>
  </div>
<% else %>
  <div class="container-search" style="position: relative; left:27px">
    <button class="btn btn-flat" data-toggle="collapse" data-target="#collapseDropDownSearch">Start New Journey</button>
    <div class="collapse" id="collapseDropDownSearch">
      <div class="card-search" id = "drop-down-filtersearch">
        <%= form_with url: "/listings", method: :get, local: true, class: 'simple_form search drop-down-form' do |form| %>
          <div class="search-input">
            <label for="start">Start</label>
            <%= form.text_field :start, id: "start", name: "start", required: 3%>
            <label for="end">End</label>
            <%= form.text_field :end, id: "end", name: "end", required: 3 %>
            <button type="submit" class="btn btn-ghost"><i class="fas fa-search"></i></button>
          </div>
        <% end %>
      </div>  
    </div>
  </div>
<% end %>

app/views/shared/_short-banner-2-new.html.erb
<div class="row justify-content-center">
  <div class="col-xl-12">

    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
    url(https://images.unsplash.com/photo-1605214104310-e8eeaf317e8c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1141&q=900">
    <h1>Get on your bike and start exploration today!</h1>
    <p>The best sights and eats in Singapore awaits</p>
     </div>
</div>
</div>

app/views/shared/_short-banner.html.erb
<div class="row justify-content-center">
  <div class="col-xl-12">

    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),
    url(https://images.unsplash.com/photo-1509270092120-e33cfb011c49?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1052&q=80)">
    <h1>Welcome back!</h1>
     </div>
</div>
</div>

app/views/shared/_user-avatar.html.erb
<% if user.avatar.attached? %>
<img class="card-avatar avatar-bordered" src="https://res.cloudinary.com/dcm2heeuf/image/upload/v1620723373/<%=user.avatar.key %>">
<% else %>
<img class="card-avatar avatar-bordered" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png">
<% end %>

app/views/shared/_value-prop-under-banner.html.erb
<div class="container-fluid-valuepropbox">
  <div class="col-12 card-deck">
   <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
    <div class="card valueprop">
        <img class="image-value-prop" src="https://cdn2.iconfinder.com/data/icons/green-style/30/icon_search-512.png">
        <div class="card-text">
          <h5 class="card-title">Search</h5>
          <p>Pick your itinerary from thousands of eats & sights options</p>
        </div>
    </div>
  </div>

 <div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
  <div class="card valueprop">
    <img class="image-value-prop" src="https://cdn2.iconfinder.com/data/icons/green-style/30/icon_camera-512.png">
      <div class="card-text">
        <h5 class="card-title">Explore</h5>
        <p>Customized cycling routes for (re)discovering Singapore</p>
      </div>
   </div>
 </div>

<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
  <div class="card valueprop">
    <img class="image-value-prop" src="https://cdn2.iconfinder.com/data/icons/green-style/30/icon_phone-512.png">
      <div class="card-text">
        <h5 class="card-title">Share</h5>
        <p>Don't say #bojio. Invite your pals for the next ride</p>
      </div>
    </div>
</div>

<div class="col-sm-12 col-md-6 col-lg-6 col-xl-3">
  <div class="card valueprop">
    <img class="image-value-prop" src="https://cdn2.iconfinder.com/data/icons/green-style/30/icon_heart-512.png">
        <div class="card-text">
          <h5 class="card-title">Support Local</h5>
          <p>Send your love to local F&B. Keep the kampung spirit alive</p>
      </div>
    </div>
  </div>
</div>
</div>