config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :listings, only: [ :index ]
  resources :journeys, only: [ :index, :show, :create, :edit, :update, :destroy] do
    member do
      get :route_email
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/my-journeys', to: 'journeys#my_journeys'
  get '/editorial', to: 'pages#editorial'

end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user, optional: true
  has_many :itineraries, dependent: :destroy
  has_many :listings, through: :itineraries
  validates :name, presence: true
  validates :origin, presence: true
  validates :destination, presence: true

end

app/controllers/journeys_controller.rb
require 'json'
require 'open-uri'
require 'fast_polylines'
require 'geocoder'

class JourneysController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def my_journeys
    @journeys = Journey.where(user: current_user)
  end

  def index
    @journeys = Journey.all
  end

  def show
    @journey = Journey.find(params[:id])
    start_end(@journey.origin, @journey.destination)
    listing_markers(@journey.listings)
  end

  def create
    @journey = Journey.new(journey_params)
    @journey.user = current_user
    start_end(params[:journey][:origin], params[:journey][:destination])
    @journey.listings = Listing.where(id: params[:listing_ids]).near(@start, 20)

    listing_coords = @journey.listings.map do |listing|
      ["#{listing.longitude},#{listing.latitude};"]
    end

    screenshot(listing_coords)

    @journey.route_url = @url_params.join('')
    check_journey_valid
  end

  def edit
    @journey = Journey.find(params[:id])
    @categories = Category.all
    start_end(@journey.origin, @journey.destination) #function created below for finding the coords for start and end
    listing_eats_sights #function created below for storing the eats and sights
    markers = @listingeats + @listingsights
    #function created below for storing the details of listing and sending to javascript
    listing_markers(Listing.where(id: markers)) # arrange selected markers according to proximity to origin
    authorize @journey
  end

  def update
    @journey = Journey.find(params[:id])
    @journey.update(journey_params)
    start_end(@journey.origin, @journey.destination)
    @journey.listings = Listing.where(id: params[:journey][:listing_ids]).near(@start, 20)
    listing_coords = @journey.listings.map do |listing|
      ["#{listing.longitude},#{listing.latitude};"]
    end

    screenshot(listing_coords)

    @journey.route_url = @url_params.join('')
    if @journey.name?
      if @journey.save
        redirect_to journey_path(@journey)
      else
        flash.now[:notice] = "Error in saving the Journey"
        redirect_to edit_journey_path(@journey)
      end
    else
      flash.now[:notice] = "Enter Your Journey's Name"
      redirect_to edit_journey_path(@journey)
    end
    authorize @journey
  end

  def destroy
    @journey = Journey.find(params[:id])
    @journey.destroy
    redirect_to my_journeys_path
  end


  def route_email
    @journey = Journey.find(params[:id])
    JourneyMailer.with(journey: @journey).route_email.deliver_now
    redirect_to journey_path(@journey)
    flash.now[:notice] = "Journey emailed!"
  end

 private

  def start_end(origin, destination)
    start_location = Geocoder.search("#{origin},Singapore")
    @start = start_location.first.coordinates

    end_location =  Geocoder.search("#{destination},Singapore")
    @end = end_location.first.coordinates
    @fit_points = [@start, @end]
  end

  def listing_markers(markers)
    @listing_markers = markers.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        category: listing.category.name,
        id: listing.id,
        info_window: render_to_string(partial:"shared/info_window", locals: { listing: listing })
      }
    end
  end

 def listing_eats_sights
    center = Geocoder::Calculations.geographic_center([@start, @end])
    distance= Geocoder::Calculations.distance_between(@start, @end)
    box = Geocoder::Calculations.bounding_box(center, (distance/1.9))

    @listingeats = Listing.where(category: Category.last).within_bounding_box(box).by_tag_eats(params[:tag_eats]).near(@start)
    @listingsights = Listing.where(category: Category.first).within_bounding_box(box).by_tag_sights(params[:tag_sights]).near(@start)
  end

  def check_journey_valid
    if @journey.name?
      if @journey.save
        redirect_to journey_path(@journey)
      else
        flash.now[:notice] = "Error in saving the Journey"
        redirect_to listings_path
      end
    else
      flash.now[:notice] = "Enter Your Journey's Name"
      redirect_to listings_path
    end
  end

  def journey_params
    params.require(:journey).permit!
  end

  def screenshot(listing_coords)
    # obtain turn by turn coordinates from mapbox
    url_search_params = [
      'https://api.mapbox.com/optimized-trips/v1/mapbox/cycling/',
      @start[1],
      ',',
      @start[0],
      ';',
      listing_coords.join(''),
      @end[1],
      ',',
      @end[0],
      "?source=first&destination=last&roundtrip=false&steps=true&geometries=geojson&access_token=#{ENV['MAPBOX_API_KEY']}",
      ]
      # parse the json from mapbox
      url_search = url_search_params.join("")
      raw_json = open(url_search).read
      parsed_json = JSON.parse(raw_json)
      decoded_waypoints = parsed_json['trips'].first['geometry']['coordinates']
      reverse_decoded_waypoints = decoded_waypoints.map do |coord|
        coord.reverse
      end

    # obtain screenshot url
    @url_params = [
      'https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/',
      'pin-s+6aec84',
      '(',
      @start[1],
      ',',
      @start[0],
      ')',
      ',',
      'pin-s+02550c',
      '(',
      @end[1],
      ',',
      @end[0],
      ')',
      ',',
      "path-5+5E2BFF-0.7(#{CGI.escape FastPolylines.encode(reverse_decoded_waypoints)})",
      '/auto/1200x630?',
      "access_token=#{ENV['MAPBOX_API_KEY']}"
    ]
  end
end

app/views/journeys/edit.html.erb
<div class="container-fluid journey-edit">
  <div class="row">
    <div class="col-lg-4">
      <div class="d-flex justify-content-around mt-3">
        <h3>Eats<img src="https://cdn4.iconfinder.com/data/icons/map-pins-2/256/21-512.png"></h3>
        <h3>Sights<img src="https://cdn4.iconfinder.com/data/icons/map-pins-2/256/30-512.png"></h3>
      </div>
      <div class="text-right filter-parent">
        <button class="btn btn-filter filter" data-toggle="collapse" data-target="#collapseDropDown">
          <i class="fas fa-sliders-h"></i>
        </button>
      </div>
      <div class="collapse" id="collapseDropDown">
        <div class="card card-body" id = "drop-down-filter">
        <%= form_with url: "/listings", method: :get, local: true, class: 'simple_form search drop-down-form' do |form| %>
          <div class="form-group">
            <label for="eat-tags">Select your tag for Eats</label>
            <%= form.select :tag_eats, ["Bakeries", "Fastfood", "Restaurants", "Beverages", "Cafés", "Supermarkets", "Hawkers" ], {:include_blank => 'All'}, class: "form-control", id: "eat-tags", prompt: "All" %>
          </div>
          <div class="form-group">
            <label for="sight-tags">Select your tag Sights</label>
            <%= form.select :tag_sights, ["Monuments", "Museums", "Parks"], {:include_blank => 'All'}, class: "form-control", id: "sight-tags" %>
          </div>
          <%= form.hidden_field :start, value: params[:start]%>
          <%= form.hidden_field :end, value: params[:end] %>
          <button type="submit" class="btn btn-block btn-success mb-0">Submit</button>
        <% end %>          
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <div class="row">
            <div class="routes-grid">
              <% if @listingeats.size == 0 %>
                <h5>No listings available</h5>
                <h5>Try again!</h5>
              <% else %>
                <%= render @listingeats %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="row">
            <div class="routes-grid">
              <% if @listingsights.size == 0 %>
                <h5>No listings available</h5>
                <h5>Try again!</h5>
              <% else %>
                <%= render @listingsights %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="sticky">
        <div class="row" style="align-items: center">
          <div class="col-lg-12">
            <%= simple_form_for @journey do |f| %>
              <%= f.input :name, label: "Name Your Journey", label_html: { class: 'journey-create-name-edit' }, required: :true %>
              <%= f.association :listings, as: :check_boxes %>
              <small>
                <%= f.input :privacy, label: 'Visible to public',
                checked_value: false, unchecked_value: true %>
              </small>
              <%= f.hidden_field :origin, value: @journey.origin %>
              <%= f.hidden_field :destination, value: @journey.destination %>
              <%= f.submit "Submit!", class: "btn btn-success btn-block" %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <%= render 'shared/map',
              start: @start,
              end_location: @end,
              fit_points: @fit_points,
              listing_markers: @listing_markers
          %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/journeys/index.html.erb
<div class="card-group">
      <h3>Our Popular Routes<small><em><%= link_to "(see all)", journeys_path %></em></small></h3>
  </div>

    <!-- LIST ALL PUBLIC ROUTES - PRIVACY FALSE -->
 <div class="container-landing">
    <% @journeys.where(privacy: false).limit(10).each do |journey| %>
      <div class="card-landing">
        <img class="card-img-landing" src="<%=journey.route_url%>">
           <div class="card-avatar-landing">
              <% user = User.find(journey.user_id)%>
              <%= render "shared/user-avatar", user: user %>
            </div>
            <h6 class="card-title-landing">
              <%= link_to "#{journey.name}", journey %>
            </h6>
            <div class="card-body-landing">
              <small>From: <%= journey.origin.titleize %> </small>
              <small>To: <%= journey.destination.titleize %></small>
            </div>
          <div class="btn btn-success"><%= link_to "see route", journey %></div>
      </div>
    <% end %>
  </div>

app/views/journeys/my_journeys.html.erb
<div class="card-group">
  <div class="col-xl-12">
    <h3>Your Journeys</h3>
  </div>

  <div class="col-12">
    <div class="container-landing">
      <% if @journeys.size == 0 %>
      <h5>Awww... Snap! You've yet to create any journey</h5>
      <% else %>
      <% @journeys.each do |listing| %>
      <div class="card-landing">
        <img class="card-img-landing" src="<%=listing.route_url%>">
        <h6 class="card-title-landing">
          <%= link_to "#{listing.name}", "/journeys/#{listing.id}}" %></h6>
          <div class="card-body-landing">
            <small>From: <%= listing.origin.capitalize %> </small>
            <small>To: <%= listing.destination.capitalize %></small>
          </div>
          <div class="card-footer-landing">
           <small>
            <% if listing.privacy == true %>
            Private route
            <% else %>
            Visible to public
            <% end %></br>
          </small>
        </div>
        <div class="btn btn-success"><%= link_to "see route", "/journeys/#{listing.id}}" %></div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/journeys/show.html.erb
<% content_for :meta_title, "Check out cycling route #{@journey.name} on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Discover sights and eats from #{@journey.origin.capitalize} to #{@journey.destination.capitalize}!" %>
<% content_for :meta_image, @journey.route_url %>

<div class="row" id="map-row">

  <div class="col-xl-4">

    <div class="row" style="padding-left: 10px; padding-right: 10px">
      <div class="col-xl-8">

        <div class="container">
          <h5><%= @journey.name  %></h5>
          <p>From: <%= @journey.origin.capitalize %></br>
           To: <%= @journey.destination.capitalize %></p>
         </div>

       </div>
       <div class="col-xl-4 avatar">
        <div class="avatar">
          <% user = User.find(@journey.user_id)%>
          <% if user.avatar.attached? %>
          <img class="avatar-xl" src="https://res.cloudinary.com/dcm2heeuf/image/upload/v1620723373/<%=user.avatar.key %>">
          <% else %>
          <img class="avatar-xl" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png">
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row g-0">
        <div class="col-xl-6">
          <div class="text-center">
            <h6>Eats</h6>
          </div>
          <div class="d-flex flex-column align-items-center">
            <% @journey.listings.where(category: Category.last).each do |listing| %>
            <div class="card-small d-flex flex-column justify-content-between">
              <div class="card-title">
                <h6><strong><%= listing.name%></strong></h6>
              </div>
              <div class="card-text d-flex flex-column">
                <small>
                  <%= listing.address %>
                </small>
              </div>
              <div class="badge badge-pill badge-success">
                <small>
                  <%= listing.tags.map(&:name).join('') %>
                </small>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <div class="col-xl-6">
          <div class="text-center">
            <h6>Sights</h6>
          </div>
          <div class="d-flex flex-column align-items-center">
            <% @journey.listings.where(category: Category.first).each do |listing| %>
            <div class="card-small d-flex flex-column justify-content-between">
              <div class="card-title">
                <h6><strong><%= listing.name%></strong></h6>
              </div>
              <div class="card-text d-flex flex-column">
                <small>
                  <%= listing.address %>
                </small>
              </div>
              <div class="badge badge-pill badge-success">
                <small>
                  <%= listing.tags.map(&:name).join('') %>
                </small>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="row icons">
      <div class="col-xl-9">
        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v10.0" nonce="NXLjCoj3"></script>
        <div class="fb-share-button" data-href="https://ridenowrightnow.herokuapp.com/journeys/<%= @journey.id %>" data-layout="button" data-size="large"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fridenowrightnow.herokuapp.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
      </div>
      <div class="col-xl-3 icons">
        <% if user_signed_in? %>
        <%= link_to "", route_email_journey_path, class: 'fas fa-envelope' %>
        <% end %>
        <% if policy(@journey).update? %>
        <%= link_to "", edit_journey_path(@journey), class: 'fas fa-edit' %>
        <%= link_to "",
        journey_path(@journey),
        method: :delete,
        data: { confirm: "Are you sure?" }, class:"fa fa-trash" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xl-8 map-right">
    <div class="mapbox">
      <div id="map-journey"
      style="width: 100%; height: 800px; position:sticky"
      data-start="<%= @start.to_json %>"
      data-end="<%= @end.to_json %>"
      data-fitpoints="<%= @fit_points.to_json %>"
      data-listingmarkers="<%= @listing_markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div id="instructions">
    </div>
  </div>
  <div class="button-box">
    <button class="backBtn btn btn-success">Back</button>
    <button class="nextBtn btn btn-success">Next</button>
  </div>
</div>

</div>